name: Coverage ðŸ›Œ

on:
  push:
    paths:
      - "whirl/**"
      - "whirl_config/**"
      - "whirl_prompt/**"
      - "whirl_server/**"
  pull_request:
    paths:
      - "whirl/**"
      - "whirl_config/**"
      - "whirl_prompt/**"
      - "whirl_server/**"

jobs:
  coverage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout ðŸ›’
        uses: actions/checkout@v2

      - name: Toolchain ðŸ§°
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-02-20
          components: rustfmt, clippy
          override: true

      - name: Tarpaulin â›º
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - name: Upload to Codecov âœˆ
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive Coverage Results ðŸ—ƒ
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
